
- name: Setup web hosts
  hosts: all
  user: root

  roles:
    - name: geerlingguy.postgresql
      tags: postgresql
    - name: geerlingguy.apache
      tags: apache
    - name: geerlingguy.php
      tags: php
    - name: local.adminer
      tags: adminer

